language: ruby
notifications:
  recipients:
    - rake-compiler@ml.commit-email.info
before_script:
  - gem update --system $RUBYGEMS_VERSION
  - gem update bundler
rvm:
  - 2.1.2
  - 2.2
  - 2.3.0
  - ruby-head
env:
  - RUBYGEMS_VERSION=2.0.14
  - RUBYGEMS_VERSION=2.2.2
  - RUBYGEMS_VERSION=2.4.1
matrix:
  allow_failures:
    - rvm: ruby-head
